### ISSUE TITLE
Dotnettency

### ISSUE THREAD

**Issue by dazinator** [amalabey/multitenancy-sample#1]
Hi,
I wondered if dotnettency ended up being useful to you for any production scenarios / applications?
If it did, let me know how it worked out, as it would be good to get a few more data points!

Many Thanks
Darrell (dotnettency author)

**Comment by amalabey** [comment]
Dotnettency worked really well for us, but the whole project took a completely different direction and a different tech stack. So, we never got the chance to run it in production though.

**Comment by dazinator** [comment]
Glad it worked well although a shame it didn't see production (from my perspective!). Thanks for the response!
